// Font Awesome configuration and re-exports
import { library, config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

// Prevent FA from adding its own CSS since we're importing it manually
config.autoAddCss = false;

// Re-export everything needed
export { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
export type { FontAwesomeIconProps } from "@fortawesome/react-fontawesome";

// Re-export commonly used solid icons
export {
  faUser,
  faEnvelope,
  faLock,
  faEye,
  faEyeSlash,
  faSearch,
  faCheck,
  faTimes,
  faPlus,
  faMinus,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faArrowRight,
  faArrowLeft,
  faCog,
  faGear,
  faBell,
  faHeart,
  faStar,
  faHome,
  faSignOutAlt,
  faSignInAlt,
  faUserPlus,
  faTrash,
  faEdit,
  faPen,
  faSave,
  faDownload,
  faUpload,
  faSpinner,
  faCircleNotch,
  faExclamationTriangle,
  faExclamationCircle,
  faInfoCircle,
  faCheckCircle,
  faTimesCircle,
  faQuestionCircle,
  faCalendar,
  faClock,
  faPhone,
  faMapMarkerAlt,
  faLink,
  faExternalLinkAlt,
  faCopy,
  faFilter,
  faSort,
  faBars,
  faEllipsisV,
  faEllipsisH,
  faCreditCard,
  faShoppingCart,
  faTag,
  faTags,
  faFolder,
  faFile,
  faImage,
  faCamera,
  faPaperclip,
  faPaperPlane,
  faComment,
  faComments,
  faShare,
  faThumbsUp,
  faThumbsDown,
  faBolt,
  faShield,
  faShieldAlt,
  faKey,
  faFingerprint,
  faUserCircle,
  faUserCog,
  faUsers,
  faBuilding,
  faBriefcase,
  faGlobe,
  faLanguage,
  faPalette,
  faMoon,
  faSun,
  faDesktop,
  faMobile,
  faTablet,
  faLaptop,
  faCode,
  faTerminal,
  faDatabase,
  faServer,
  faCloud,
  faCloudUploadAlt,
  faCloudDownloadAlt,
  faWifi,
  faRss,
  faHashtag,
  faAt,
  faDollarSign,
  faPercent,
} from "@fortawesome/free-solid-svg-icons";

// Re-export commonly used regular icons
export {
  faUser as faUserRegular,
  faEnvelope as faEnvelopeRegular,
  faHeart as faHeartRegular,
  faStar as faStarRegular,
  faBell as faBellRegular,
  faCalendar as faCalendarRegular,
  faClock as faClockRegular,
  faComment as faCommentRegular,
  faComments as faCommentsRegular,
  faFolder as faFolderRegular,
  faFile as faFileRegular,
  faImage as faImageRegular,
  faThumbsUp as faThumbsUpRegular,
  faThumbsDown as faThumbsDownRegular,
  faBookmark as faBookmarkRegular,
  faCircle as faCircleRegular,
  faSquare as faSquareRegular,
  faCheckCircle as faCheckCircleRegular,
  faTimesCircle as faTimesCircleRegular,
  faQuestionCircle as faQuestionCircleRegular,
  faCopy as faCopyRegular,
  faEye as faEyeRegular,
  faEyeSlash as faEyeSlashRegular,
} from "@fortawesome/free-regular-svg-icons";

// Re-export commonly used brand icons
export {
  faGoogle,
  faGithub,
  faFacebook,
  faTwitter,
  faLinkedin,
  faInstagram,
  faYoutube,
  faTiktok,
  faDiscord,
  faSlack,
  faMicrosoft,
  faApple,
  faAmazon,
  faSpotify,
  faDropbox,
  faTwitch,
  faReddit,
  faPinterest,
  faSnapchat,
  faWhatsapp,
  faTelegram,
  faStripe,
  faPaypal,
  faCcVisa,
  faCcMastercard,
  faCcAmex,
  faReact,
  faVuejs,
  faAngular,
  faNodeJs,
  faPython,
  faJs,
  faHtml5,
  faCss3Alt,
  faSass,
  faDocker,
  faAws,
  faGitAlt,
  faNpm,
  faFigma,
} from "@fortawesome/free-brands-svg-icons";

// Export library for manual icon registration if needed
export { library };
